# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ Aula_2 ]
  pull_request:
    branches: [ Aula_2 ]
 
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build-DB
        run: docker-compose build

      - name: Create-DB
        run: docker-compose up -d

      - name: Test
        run: go test -v main_test.go
